### ISSUE TITLE
Styling of the Purchase Buttons on a Book Page

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/Genesis-Author-Pro#13]
### What is happening now?

From https://github.com/copyblogger/synthesis-platform/issues/3141

The styling of the purchase buttons on the book page need slightly changing so that there's some space between them. Noticed this was a problem on a few themes including Agency and Rainmaker Pro. 

![rm-01](https://cloud.githubusercontent.com/assets/13838446/15298575/db3b3e88-1b97-11e6-8198-fc9f5efac807.png)
### Specific Steps to reproduce the issue:
1. Create a new book page and view it on the front end to view the position of the buttons. 
### What is the expected behavior?

More spacing around the buttons. On some of the themes, the buttons appear underneath each other.

**Comment by dreamwhisper** [comment]
I'd recommend making the CSS for this section more specific:

``` css
.button-book {
  display: block;
  margin: 10px auto;
  text-align: center;
  width: 100%;
}
```

to

``` css
.book-details .button-book {
  display: block;
  margin: 10px auto;
  text-align: center;
  width: 100%;
}
```

Should be added to the WP plugin too since it will display this way outside of the Author theme.

Edit: corrected original CSS.
