### ISSUE TITLE
Pagination clearing

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/Genesis-Author-Pro#18]
### What is happening now?

On a number of themes, the archive navigation appears at the side of the books depending on the number of books on the page.

![rm-2](https://cloud.githubusercontent.com/assets/13838446/15317448/6f52fc10-1c19-11e6-9c51-c5ae8cff4700.png)
### What is the expected behavior?

The navigation should appear underneath the books. 

This should go into both the WP plugin and RM.

``` css
.post-type-archive-books .archive-pagination {
    clear: both;
}
```

**Comment by dreamwhisper** [comment]
Actually, this won't work unless we have a standard body class across archive pages. 
- Main Archive
- Author Archive
- Book Tag Archive
- Book Series Archive

**Comment by dreamwhisper** [comment]
I'm blind, we had one:

``` css
.genesis-author-pro .archive-pagination {
    clear: both;
}
```
